

service: lesson3

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getUser:
    handler: lambdas/getUser.handler
    events:
      - http:
          path: /get-user/{ID}
          method: GET
          cors: true
