service: lesson5

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

custom:
  tableName: player-points

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName} # ${} is called referencing
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
